"""empty message

Revision ID: 1a37b4ceafd8
Revises: 602569b8223f
Create Date: 2018-08-12 14:37:54.986133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a37b4ceafd8'
down_revision = '602569b8223f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'zipcodes', ['zipcode'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'zipcodes', type_='unique')
    # ### end Alembic commands ###
