"""empty message

Revision ID: 602569b8223f
Revises: 4dbce98c6723
Create Date: 2018-08-12 14:30:24.183690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '602569b8223f'
down_revision = '4dbce98c6723'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zipcode_counties',
    sa.Column('clerk_id', sa.Integer(), nullable=False),
    sa.Column('zipcode_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clerk_id'], ['clerks.id'], ),
    sa.ForeignKeyConstraint(['zipcode_id'], ['zipcodes.id'], ),
    sa.PrimaryKeyConstraint('clerk_id', 'zipcode_id')
    )
    op.drop_constraint('zipcodes_county_id_fkey', 'zipcodes', type_='foreignkey')
    op.drop_column('zipcodes', 'county_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zipcodes', sa.Column('county_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('zipcodes_county_id_fkey', 'zipcodes', 'clerks', ['county_id'], ['id'])
    op.drop_table('zipcode_counties')
    # ### end Alembic commands ###
