"""empty message

Revision ID: 7e02c1d7810c
Revises: 8c7f8fa92c20
Create Date: 2018-10-06 11:49:25.549466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e02c1d7810c'
down_revision = '8c7f8fa92c20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registrants', sa.Column('redacted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registrants', 'redacted_at')
    # ### end Alembic commands ###
