"""empty message

Revision ID: 8c3766231a8f
Revises: a4181f33a8e3
Create Date: 2018-06-04 09:52:49.849504

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8c3766231a8f'
down_revision = 'a4181f33a8e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registrants', sa.Column('session_id', postgresql.UUID(), nullable=False))
    op.create_unique_constraint(None, 'registrants', ['session_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'registrants', type_='unique')
    op.drop_column('registrants', 'session_id')
    # ### end Alembic commands ###
