"""empty message

Revision ID: bccd8c2ff598
Revises: 0f2ef5e4ecfd
Create Date: 2022-07-29 09:03:50.233767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bccd8c2ff598'
down_revision = '0f2ef5e4ecfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registrants', sa.Column('user_agent', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registrants', 'user_agent')
    # ### end Alembic commands ###
