"""empty message

Revision ID: d5059cfd2e07
Revises: 1a37b4ceafd8
Create Date: 2018-08-12 14:55:15.606991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5059cfd2e07'
down_revision = '1a37b4ceafd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zipcode_counties', sa.Column('voter_count', sa.Integer(), nullable=True))
    op.drop_column('zipcodes', 'voter_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zipcodes', sa.Column('voter_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('zipcode_counties', 'voter_count')
    # ### end Alembic commands ###
