on:
  pull_request:
  push:
    branches:
      - master

# Cancel redundant builds on same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

name: Test and Lint
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9, 3.10.0]
        node-version: [14.18]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup env
        run: echo USPS_USER_ID=${{ secrets.USPS_USER_ID }} >> .env-ci && cat .env-ci | grep -v ^# >> $GITHUB_ENV
      - name: Add /etc/hosts entries
        run: |
          echo '127.0.0.1  ksvotes-postgres' | sudo tee -a /etc/hosts
          echo '127.0.0.1  redis' | sudo tee -a /etc/hosts
          echo '127.0.0.1  test.ksvotes.org' | sudo tee -a /etc/hosts
          cat /etc/hosts
      - name: Start CI docker compose
        run: make ci-start
        env:
          DOCKER_BUILDKIT: 1
          ENV_NAME: ci
      - name: Install Chrome driver
        run: |
          export CHROME_MAIN_VERSION=`google-chrome-stable --version | sed -E 's/(^Google Chrome |\.[0-9]+ )//g'`
          export CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_MAIN_VERSION"`
          curl "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O
          unzip chromedriver_linux64.zip -d ~/bin
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --yes --no-install-recommends postgresql-client
          make deps
      - name: Run tests
        run: make ci-test jstest
      - name: Docker logs
        run: docker logs web --details
        if: failure()
      - name: Stop CI docker compose
        run: |
          docker exec web ls -l
          make ci-stop
        if: always()
